### ISSUE TITLE
Docker command example

### ISSUE THREAD

**Issue by simplylizz** [trivago/hamara#14]
```bash
export GRAFANA_API_KEY=<your API key here>
docker run --rm trivago/hamara export --host=localhost:3000 --key=$GRAFANA_API_KEY > datasources.yaml
cat datasources.yaml
```

It should be rather something like this:
```bash
export GRAFANA_API_KEY=<your API key here>
docker run --rm trivago/hamara ./hamara export --host=host.docker.internal:3000 --key=$GRAFANA_API_KEY > datasources.yaml
cat datasources.yaml
```

Added a binary and changed host, alternatively `--network host` could be used.

**Comment by nickorlow** [comment]
Ran into this issue and this fixed it, note that if you're using Docker on linux, you also need to add `--add-host host.docker.internal:host-gateway` to the `docker run` command, as host.docker.internal is only created by default on docker for mac & windows
